name: Sensor Mega

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v2
      - name: Install Arduino AVR Core (for Mega)
        shell: bash  # Use Git Bash for consistent CLI syntax
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
          arduino-cli lib install SD
          arduino-cli lib RTClib
          arduino-cli lib SD
          arduino-cli lib DallasTemperature
          arduino-cli lib DHTlib
          arduino-cli lib ArduinoJson
      - name: Compile Sketch for Arduino Mega
        shell: bash
        run: |
          arduino-cli compile --fqbn arduino:avr:mega ./Sensors_20171109_copy
